Kubernetes 1
Otus-DevOps-2017-11/lakostin_microservices pull request #11
Opened 2018-03-25 20:00 UTC by lakostin

Выполнен туториал kubernetes the hard way.

2018-03-26 08:51 UTC, serjs approved these changes
Поторопился с апрувом, коммент ниже с запросом отписал

2018-03-26 09:31 UTC, serjs requested changes
Я упустил структурные изменения. Нужно подспек файлы вынести в kubernetes каталог, вместо docker/kubernetes тогда уж.

2018-04-12 09:11 UTC, serjs commented
@lakostin Привет! Тебе нужна помощь с внесением изменений, которые запрашивались?

2018-04-16 18:35 UTC, lakostin commented
Сергей, приветствую! Что такое подспек файлы?

2018-05-25 07:34 UTC, lakostin commented
Вынес kubernetes и kubernetes_the_hard_way в основной каталог.

2018-05-28 14:04 UTC, serjs commented
Приветствую! Похоже я упустил комментарий, pod spec файл это yml описание пода в Kubernetes.

2018-05-28 14:07 UTC, serjs approved these changes
PR можно закрывать, следы Hard way есть, описание также.

Запрос на изменения судя по истории был выполнен в рамке 31 ДЗ

2018-05-28 14:08 UTC, serjs approved these changes
PR можно закрывать, следы Hard way есть, описание также.

Запрос на изменения судя по истории был выполнен в рамке 31 ДЗ

2018-05-28 17:20 UTC, merged